name: Build and push Docker image to Docker Hub
on:
  release:
    types: [created]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for arm64
        run: docker buildx build --platform linux/arm64 -t user/repo:${{ github.event.release.tag_name }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for amd64
        run: docker buildx build --platform linux/amd64 -t user/repo:${{ github.event.release.tag_name }} .

      - name: Push Docker image to Docker Hub
        run: docker push user/repo:${{ github.event.release.tag_name }}
